* Question Section 1
** How are the textures coordinates mapped on the bunny? Can you see what geometry was used?
   linear map.
** What kind of procedural texture did you make?
   Pshycadelic bunny inspired by the psychadelic teapot by Ingemar.
* Question Section 2
** How can you make a texture repeat multiple times over the bunny?
   By multiplying the amount of time we read the texture.
** Why can't we just pass the texture object to the shader? .....
   We have limited memory, loading to many textures will overload it.
* Question Section 3
** How did you move the bunny to get it in view?
   Move it back in Z-direction.
* Question Section 4
** Given a certain vector for v, is there some place you can't place the camera?
   No
* Question Section 5
** Did you implement your light calculations in the vertex or fragment shader? So, which kind of shading did you implement?
   In the fragment shader. PHONG shading.
** Some geometry data must be vec4, others are just as well vec3's. Which ones, and why? How about vertices, light source, normal vectors...?
   If we don't intend to use translation/alpha we can use
   vec3. Vertices, light source, and normal vectors may be vec3 if so
   is wished. Color is usually vec4.
* Question Section 6
** Was the difference big? If not, why?
    no big difference although with a brighter light the gouraud shading
    is a little brighter along the edges. It not being that different may
    be because the texture hiding imperfections or the model being small
    in the window so it's difficult to see.
* Question Section 7
** If you rotate an object or rotate the camera, what matrices are affected?
    the mdlMatrix aka model-to-view matrix is affected by moving the object,
    while the lookAt/camera matrix is affected by moving the camera.
